
set_property PACKAGE_PIN B8 [get_ports FPGA_CLK_50MHZ]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_CLK_50MHZ]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SCLK[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SCLK[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SCLK[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SCLK[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SCLK[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SCLK[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SCLK[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SCLK[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SCLK[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SCLK[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SCLK[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SCLK[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SCLK[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SCLK[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SCLK[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SCLK[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SDIO0[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SDIO0[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SDIO0[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SDIO0[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SDIO0[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SDIO0[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SDIO0[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SDIO0[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SDIO0[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SDIO0[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SDIO0[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SDIO0[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SDIO0[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SDIO0[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SDIO0[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SDIO0[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SDIO2[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SDIO2[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SDIO2[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SDIO2[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SDIO2[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SDIO2[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SDIO2[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SDIO2[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SDIO2[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SDIO2[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SDIO2[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SDIO2[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SDIO2[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SDIO2[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SDIO2[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SDIO2[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SDIO3[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SDIO3[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SDIO3[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SDIO3[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SDIO3[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SDIO3[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SDIO3[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SDIO3[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SDIO3[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SDIO3[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SDIO3[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SDIO3[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SDIO3[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SDIO3[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SDIO3[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_SDIO3[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_nCS[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_nCS[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_nCS[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_nCS[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_nCS[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_nCS[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_nCS[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_nCS[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_nCS[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_nCS[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_nCS[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_nCS[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_nCS[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_nCS[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_nCS[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_nCS[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_nLOAD[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_nLOAD[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_nLOAD[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_nLOAD[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_nLOAD[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_nLOAD[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_nLOAD[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_nLOAD[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_nLOAD[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_nLOAD[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_nLOAD[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_nLOAD[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_nLOAD[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_nLOAD[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_nLOAD[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_nLOAD[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_nRST[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_nRST[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_nRST[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_nRST[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_nRST[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_nRST[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_nRST[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_nRST[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_nRST[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_nRST[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_nRST[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_nRST[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_nRST[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_nRST[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_nRST[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DAC_nRST[0]}]
set_property PACKAGE_PIN D10 [get_ports RST_SW]
set_property IOSTANDARD LVCMOS33 [get_ports RST_SW]
set_property PACKAGE_PIN T9 [get_ports STS1_LED_GREEN]
set_property IOSTANDARD LVCMOS33 [get_ports STS1_LED_GREEN]
set_property PACKAGE_PIN A8 [get_ports TP_CLK_TST]
set_property IOSTANDARD LVCMOS33 [get_ports TP_CLK_TST]
set_property PACKAGE_PIN V14 [get_ports {BUS_DATA[15]}]
set_property PACKAGE_PIN U14 [get_ports {BUS_DATA[14]}]
set_property PACKAGE_PIN V11 [get_ports {BUS_DATA[13]}]
set_property PACKAGE_PIN V10 [get_ports {BUS_DATA[12]}]
set_property PACKAGE_PIN V12 [get_ports {BUS_DATA[11]}]
set_property PACKAGE_PIN U12 [get_ports {BUS_DATA[10]}]
set_property PACKAGE_PIN U11 [get_ports {BUS_DATA[9]}]
set_property PACKAGE_PIN T11 [get_ports {BUS_DATA[8]}]
set_property PACKAGE_PIN V17 [get_ports {BUS_DATA[7]}]
set_property PACKAGE_PIN U16 [get_ports {BUS_DATA[6]}]
set_property PACKAGE_PIN U18 [get_ports {BUS_DATA[5]}]
set_property PACKAGE_PIN U17 [get_ports {BUS_DATA[4]}]
set_property PACKAGE_PIN V16 [get_ports {BUS_DATA[3]}]
set_property PACKAGE_PIN N16 [get_ports {BUS_DATA[2]}]
set_property PACKAGE_PIN N15 [get_ports {BUS_DATA[1]}]
set_property PACKAGE_PIN M17 [get_ports {BUS_DATA[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BUS_DATA[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BUS_DATA[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BUS_DATA[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BUS_DATA[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BUS_DATA[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BUS_DATA[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BUS_DATA[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BUS_DATA[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BUS_DATA[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BUS_DATA[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BUS_DATA[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BUS_DATA[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BUS_DATA[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BUS_DATA[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BUS_DATA[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BUS_DATA[0]}]

set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]
set_property BITSTREAM.CONFIG.SPI_32BIT_ADDR YES [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.CONFIG.OVERTEMPPOWERDOWN ENABLE [current_design]
set_property CONFIG_MODE SPIx4 [current_design]

create_clock -period 20.000 -name FPGA_CLK_50MHZ -waveform {0.000 10.000} [get_ports FPGA_CLK_50MHZ]
set_input_delay -clock [get_clocks FPGA_CLK_50MHZ] -min -add_delay 2.000 [get_ports RST_SW]
set_input_delay -clock [get_clocks FPGA_CLK_50MHZ] -max -add_delay 15.000 [get_ports RST_SW]


set_output_delay -clock [get_clocks FPGA_CLK_50MHZ] -min -add_delay -5.000 [get_ports STS1_LED_GREEN]
set_output_delay -clock [get_clocks FPGA_CLK_50MHZ] -max -add_delay 2.000 [get_ports STS1_LED_GREEN]
set_output_delay -clock [get_clocks FPGA_CLK_50MHZ] -min -add_delay -5.000 [get_ports TP_CLK_TST]
set_output_delay -clock [get_clocks FPGA_CLK_50MHZ] -max -add_delay 2.000 [get_ports TP_CLK_TST]

set_property PACKAGE_PIN B7 [get_ports {DAC_nCS[0]}]
set_property PACKAGE_PIN D7 [get_ports {DAC_nCS[1]}]
set_property PACKAGE_PIN D5 [get_ports {DAC_nCS[2]}]
set_property PACKAGE_PIN G2 [get_ports {DAC_nCS[3]}]
set_property PACKAGE_PIN G4 [get_ports {DAC_nCS[4]}]
set_property PACKAGE_PIN H5 [get_ports {DAC_nCS[5]}]
set_property PACKAGE_PIN N1 [get_ports {DAC_nCS[6]}]
set_property PACKAGE_PIN U4 [get_ports {DAC_nCS[7]}]
set_property PACKAGE_PIN T4 [get_ports {DAC_nCS[8]}]
set_property PACKAGE_PIN R1 [get_ports {DAC_nCS[9]}]
set_property PACKAGE_PIN V9 [get_ports {DAC_nCS[10]}]
set_property PACKAGE_PIN B11 [get_ports {DAC_nCS[11]}]
set_property PACKAGE_PIN A16 [get_ports {DAC_nCS[12]}]
set_property PACKAGE_PIN H16 [get_ports {DAC_nCS[13]}]
set_property PACKAGE_PIN J13 [get_ports {DAC_nCS[14]}]
set_property PACKAGE_PIN G18 [get_ports {DAC_nCS[15]}]
set_property PACKAGE_PIN C6 [get_ports {DAC_nRST[0]}]
set_property PACKAGE_PIN E5 [get_ports {DAC_nRST[1]}]
set_property PACKAGE_PIN B3 [get_ports {DAC_nRST[2]}]
set_property PACKAGE_PIN D2 [get_ports {DAC_nRST[3]}]
set_property PACKAGE_PIN G6 [get_ports {DAC_nRST[4]}]
set_property PACKAGE_PIN K1 [get_ports {DAC_nRST[5]}]
set_property PACKAGE_PIN L3 [get_ports {DAC_nRST[6]}]
set_property PACKAGE_PIN U1 [get_ports {DAC_nRST[7]}]
set_property PACKAGE_PIN T3 [get_ports {DAC_nRST[8]}]
set_property PACKAGE_PIN M4 [get_ports {DAC_nRST[9]}]
set_property PACKAGE_PIN V6 [get_ports {DAC_nRST[10]}]
set_property PACKAGE_PIN C12 [get_ports {DAC_nRST[11]}]
set_property PACKAGE_PIN B17 [get_ports {DAC_nRST[12]}]
set_property PACKAGE_PIN D15 [get_ports {DAC_nRST[13]}]
set_property PACKAGE_PIN D17 [get_ports {DAC_nRST[14]}]
set_property PACKAGE_PIN E18 [get_ports {DAC_nRST[15]}]
set_property PACKAGE_PIN D18 [get_ports {DAC_nLOAD[15]}]
set_property PACKAGE_PIN K13 [get_ports {DAC_nLOAD[14]}]
set_property PACKAGE_PIN C15 [get_ports {DAC_nLOAD[13]}]
set_property PACKAGE_PIN A15 [get_ports {DAC_nLOAD[12]}]
set_property PACKAGE_PIN B12 [get_ports {DAC_nLOAD[11]}]
set_property PACKAGE_PIN U9 [get_ports {DAC_nLOAD[10]}]
set_property PACKAGE_PIN N4 [get_ports {DAC_nLOAD[9]}]
set_property PACKAGE_PIN T5 [get_ports {DAC_nLOAD[8]}]
set_property PACKAGE_PIN V1 [get_ports {DAC_nLOAD[7]}]
set_property PACKAGE_PIN N2 [get_ports {DAC_nLOAD[6]}]
set_property PACKAGE_PIN H6 [get_ports {DAC_nLOAD[5]}]
set_property PACKAGE_PIN F6 [get_ports {DAC_nLOAD[4]}]
set_property PACKAGE_PIN H2 [get_ports {DAC_nLOAD[3]}]
set_property PACKAGE_PIN B2 [get_ports {DAC_nLOAD[2]}]
set_property PACKAGE_PIN E7 [get_ports {DAC_nLOAD[1]}]
set_property PACKAGE_PIN C5 [get_ports {DAC_nLOAD[0]}]
set_property PACKAGE_PIN F18 [get_ports {DAC_SCLK[15]}]
set_property PACKAGE_PIN H17 [get_ports {DAC_SCLK[14]}]
set_property PACKAGE_PIN G16 [get_ports {DAC_SCLK[13]}]
set_property PACKAGE_PIN A13 [get_ports {DAC_SCLK[12]}]
set_property PACKAGE_PIN A11 [get_ports {DAC_SCLK[11]}]
set_property PACKAGE_PIN U7 [get_ports {DAC_SCLK[10]}]
set_property PACKAGE_PIN T1 [get_ports {DAC_SCLK[9]}]
set_property PACKAGE_PIN N5 [get_ports {DAC_SCLK[8]}]
set_property PACKAGE_PIN U3 [get_ports {DAC_SCLK[7]}]
set_property PACKAGE_PIN M3 [get_ports {DAC_SCLK[6]}]
set_property PACKAGE_PIN J5 [get_ports {DAC_SCLK[5]}]
set_property PACKAGE_PIN G3 [get_ports {DAC_SCLK[4]}]
set_property PACKAGE_PIN C2 [get_ports {DAC_SCLK[3]}]
set_property PACKAGE_PIN D4 [get_ports {DAC_SCLK[2]}]
set_property PACKAGE_PIN C4 [get_ports {DAC_SCLK[1]}]
set_property PACKAGE_PIN B6 [get_ports {DAC_SCLK[0]}]
set_property PACKAGE_PIN J17 [get_ports {DAC_SDIO0[15]}]
set_property PACKAGE_PIN G17 [get_ports {DAC_SDIO0[14]}]
set_property PACKAGE_PIN F15 [get_ports {DAC_SDIO0[13]}]
set_property PACKAGE_PIN A14 [get_ports {DAC_SDIO0[12]}]
set_property PACKAGE_PIN F13 [get_ports {DAC_SDIO0[11]}]
set_property PACKAGE_PIN U6 [get_ports {DAC_SDIO0[10]}]
set_property PACKAGE_PIN M6 [get_ports {DAC_SDIO0[9]}]
set_property PACKAGE_PIN P5 [get_ports {DAC_SDIO0[8]}]
set_property PACKAGE_PIN U2 [get_ports {DAC_SDIO0[7]}]
set_property PACKAGE_PIN M2 [get_ports {DAC_SDIO0[6]}]
set_property PACKAGE_PIN K6 [get_ports {DAC_SDIO0[5]}]
set_property PACKAGE_PIN J4 [get_ports {DAC_SDIO0[4]}]
set_property PACKAGE_PIN C1 [get_ports {DAC_SDIO0[3]}]
set_property PACKAGE_PIN E3 [get_ports {DAC_SDIO0[2]}]
set_property PACKAGE_PIN B4 [get_ports {DAC_SDIO0[1]}]
set_property PACKAGE_PIN A6 [get_ports {DAC_SDIO0[0]}]
set_property PACKAGE_PIN K15 [get_ports {DAC_SDIO2[15]}]
set_property PACKAGE_PIN H15 [get_ports {DAC_SDIO2[14]}]
set_property PACKAGE_PIN H14 [get_ports {DAC_SDIO2[13]}]
set_property PACKAGE_PIN A18 [get_ports {DAC_SDIO2[12]}]
set_property PACKAGE_PIN D12 [get_ports {DAC_SDIO2[11]}]
set_property PACKAGE_PIN T6 [get_ports {DAC_SDIO2[10]}]
set_property PACKAGE_PIN R6 [get_ports {DAC_SDIO2[9]}]
set_property PACKAGE_PIN P3 [get_ports {DAC_SDIO2[8]}]
set_property PACKAGE_PIN V5 [get_ports {DAC_SDIO2[7]}]
set_property PACKAGE_PIN L4 [get_ports {DAC_SDIO2[6]}]
set_property PACKAGE_PIN M1 [get_ports {DAC_SDIO2[5]}]
set_property PACKAGE_PIN J3 [get_ports {DAC_SDIO2[4]}]
set_property PACKAGE_PIN G1 [get_ports {DAC_SDIO2[3]}]
set_property PACKAGE_PIN F4 [get_ports {DAC_SDIO2[2]}]
set_property PACKAGE_PIN A3 [get_ports {DAC_SDIO2[1]}]
set_property PACKAGE_PIN D8 [get_ports {DAC_SDIO2[0]}]
set_property PACKAGE_PIN J15 [get_ports {DAC_SDIO3[15]}]
set_property PACKAGE_PIN C16 [get_ports {DAC_SDIO3[14]}]
set_property PACKAGE_PIN G14 [get_ports {DAC_SDIO3[13]}]
set_property PACKAGE_PIN E15 [get_ports {DAC_SDIO3[12]}]
set_property PACKAGE_PIN D13 [get_ports {DAC_SDIO3[11]}]
set_property PACKAGE_PIN R8 [get_ports {DAC_SDIO3[10]}]
set_property PACKAGE_PIN R5 [get_ports {DAC_SDIO3[9]}]
set_property PACKAGE_PIN P2 [get_ports {DAC_SDIO3[8]}]
set_property PACKAGE_PIN V4 [get_ports {DAC_SDIO3[7]}]
set_property PACKAGE_PIN L6 [get_ports {DAC_SDIO3[6]}]
set_property PACKAGE_PIN K3 [get_ports {DAC_SDIO3[5]}]
set_property PACKAGE_PIN J2 [get_ports {DAC_SDIO3[4]}]
set_property PACKAGE_PIN F1 [get_ports {DAC_SDIO3[3]}]
set_property PACKAGE_PIN F3 [get_ports {DAC_SDIO3[2]}]
set_property PACKAGE_PIN B1 [get_ports {DAC_SDIO3[1]}]
set_property PACKAGE_PIN C7 [get_ports {DAC_SDIO3[0]}]

set_output_delay -clock [get_clocks FPGA_CLK_50MHZ] -min -add_delay -5.000 [get_ports {DAC_SCLK[*]}]
set_output_delay -clock [get_clocks FPGA_CLK_50MHZ] -max -add_delay 2.000 [get_ports {DAC_SCLK[*]}]
set_output_delay -clock [get_clocks FPGA_CLK_50MHZ] -min -add_delay -5.000 [get_ports {DAC_SDIO0[*]}]
set_output_delay -clock [get_clocks FPGA_CLK_50MHZ] -max -add_delay 2.000 [get_ports {DAC_SDIO0[*]}]
set_output_delay -clock [get_clocks FPGA_CLK_50MHZ] -min -add_delay -5.000 [get_ports {DAC_nCS[*]}]
set_output_delay -clock [get_clocks FPGA_CLK_50MHZ] -max -add_delay 2.000 [get_ports {DAC_nCS[*]}]
set_output_delay -clock [get_clocks FPGA_CLK_50MHZ] -min -add_delay -5.000 [get_ports {DAC_nRST[*]}]
set_output_delay -clock [get_clocks FPGA_CLK_50MHZ] -max -add_delay 2.000 [get_ports {DAC_nRST[*]}]

set_property PACKAGE_PIN T14 [get_ports RS422_RX]
set_property IOSTANDARD LVCMOS33 [get_ports RS422_RX]
set_property PACKAGE_PIN P15 [get_ports RS422_TX]
set_property IOSTANDARD LVCMOS33 [get_ports RS422_TX]
set_property PACKAGE_PIN M13 [get_ports RS422_nEN]
set_property IOSTANDARD LVCMOS33 [get_ports RS422_nEN]
set_property PACKAGE_PIN R18 [get_ports RS422_EN]
set_property PACKAGE_PIN T10 [get_ports STS1_LED_YELLO]
set_property IOSTANDARD LVCMOS33 [get_ports STS1_LED_YELLO]
set_property IOSTANDARD LVCMOS33 [get_ports RS422_EN]

set_input_delay -clock [get_clocks FPGA_CLK_50MHZ] -min -add_delay 2.000 [get_ports RS422_RX]
set_input_delay -clock [get_clocks FPGA_CLK_50MHZ] -max -add_delay 2.000 [get_ports RS422_RX]
set_output_delay -clock [get_clocks FPGA_CLK_50MHZ] -min -add_delay -5.000 [get_ports RS422_TX]
set_output_delay -clock [get_clocks FPGA_CLK_50MHZ] -max -add_delay 2.000 [get_ports RS422_TX]
set_output_delay -clock [get_clocks FPGA_CLK_50MHZ] -min -add_delay -5.000 [get_ports STS1_LED_YELLO]
set_output_delay -clock [get_clocks FPGA_CLK_50MHZ] -max -add_delay 2.000 [get_ports STS1_LED_YELLO]

