set_property PACKAGE_PIN T9 [get_ports led_ok]
set_property PACKAGE_PIN T10 [get_ports led_err]
set_property PACKAGE_PIN B8 [get_ports clk]
set_property PACKAGE_PIN T14 [get_ports rs422_rx]
set_property PACKAGE_PIN P15 [get_ports rs422_tx]
set_property PACKAGE_PIN D10 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports led_err]
set_property IOSTANDARD LVCMOS33 [get_ports led_ok]
set_property IOSTANDARD LVCMOS33 [get_ports rs422_rx]
set_property IOSTANDARD LVCMOS33 [get_ports rs422_tx]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]

set_property PACKAGE_PIN R18 [get_ports rs422_en]
set_property PACKAGE_PIN M13 [get_ports rs422_nen]
set_property IOSTANDARD LVCMOS33 [get_ports rs422_en]
set_property IOSTANDARD LVCMOS33 [get_ports rs422_nen]

create_clock -period 20.000 -name clk -waveform {0.000 10.000} [get_ports clk]
set_input_delay -clock [get_clocks clk] -min -add_delay 2.000 [get_ports rs422_rx]
set_input_delay -clock [get_clocks clk] -max -add_delay 10.000 [get_ports rs422_rx]
set_input_delay -clock [get_clocks clk] -min -add_delay 2.000 [get_ports rst_n]
set_input_delay -clock [get_clocks clk] -max -add_delay 10.000 [get_ports rst_n]
set_output_delay -clock [get_clocks clk] -min -add_delay 0.000 [get_ports led_err]
set_output_delay -clock [get_clocks clk] -max -add_delay 2.000 [get_ports led_err]
set_output_delay -clock [get_clocks clk] -min -add_delay 0.000 [get_ports led_ok]
set_output_delay -clock [get_clocks clk] -max -add_delay 2.000 [get_ports led_ok]
set_output_delay -clock [get_clocks clk] -min -add_delay 0.000 [get_ports rs422_tx]
set_output_delay -clock [get_clocks clk] -max -add_delay 2.000 [get_ports rs422_tx]

set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
set_property BITSTREAM.CONFIG.SPI_32BIT_ADDR YES [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.CONFIG.OVERTEMPPOWERDOWN ENABLE [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
