set_property PACKAGE_PIN B6 [get_ports DAC_SCLK]
set_property PACKAGE_PIN A6 [get_ports DAC_SDIO0]
set_property PACKAGE_PIN D8 [get_ports DAC_SDIO2]
set_property PACKAGE_PIN C7 [get_ports DAC_SDIO3]
set_property PACKAGE_PIN B7 [get_ports DAC_nCS]
set_property PACKAGE_PIN C5 [get_ports DAC_nLOAD]
set_property PACKAGE_PIN C6 [get_ports DAC_nRST]
set_property PACKAGE_PIN B8 [get_ports FPGA_CLK_50MHZ]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_CLK_50MHZ]
set_property IOSTANDARD LVCMOS18 [get_ports DAC_SCLK]
set_property IOSTANDARD LVCMOS18 [get_ports DAC_SDIO0]
set_property IOSTANDARD LVCMOS18 [get_ports DAC_SDIO2]
set_property IOSTANDARD LVCMOS18 [get_ports DAC_SDIO3]
set_property IOSTANDARD LVCMOS18 [get_ports DAC_nCS]
set_property IOSTANDARD LVCMOS18 [get_ports DAC_nLOAD]
set_property IOSTANDARD LVCMOS18 [get_ports DAC_nRST]
set_property PACKAGE_PIN L18 [get_ports LATCH1_E]
set_property IOSTANDARD LVCMOS33 [get_ports LATCH1_E]
set_property PACKAGE_PIN D10 [get_ports RST_SW]
set_property IOSTANDARD LVCMOS33 [get_ports RST_SW]
set_property PACKAGE_PIN T9 [get_ports STS1_LED_GREEN]
set_property IOSTANDARD LVCMOS33 [get_ports STS1_LED_GREEN]
set_property PACKAGE_PIN A8 [get_ports TP_CLK_TST]
set_property IOSTANDARD LVCMOS33 [get_ports TP_CLK_TST]
set_property PACKAGE_PIN V14 [get_ports {BUS_DATA[15]}]
set_property PACKAGE_PIN U14 [get_ports {BUS_DATA[14]}]
set_property PACKAGE_PIN V11 [get_ports {BUS_DATA[13]}]
set_property PACKAGE_PIN V10 [get_ports {BUS_DATA[12]}]
set_property PACKAGE_PIN V12 [get_ports {BUS_DATA[11]}]
set_property PACKAGE_PIN U12 [get_ports {BUS_DATA[10]}]
set_property PACKAGE_PIN U11 [get_ports {BUS_DATA[9]}]
set_property PACKAGE_PIN T11 [get_ports {BUS_DATA[8]}]
set_property PACKAGE_PIN V17 [get_ports {BUS_DATA[7]}]
set_property PACKAGE_PIN U16 [get_ports {BUS_DATA[6]}]
set_property PACKAGE_PIN U18 [get_ports {BUS_DATA[5]}]
set_property PACKAGE_PIN U17 [get_ports {BUS_DATA[4]}]
set_property PACKAGE_PIN V16 [get_ports {BUS_DATA[3]}]
set_property PACKAGE_PIN N16 [get_ports {BUS_DATA[2]}]
set_property PACKAGE_PIN N15 [get_ports {BUS_DATA[1]}]
set_property PACKAGE_PIN M17 [get_ports {BUS_DATA[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BUS_DATA[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BUS_DATA[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BUS_DATA[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BUS_DATA[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BUS_DATA[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BUS_DATA[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BUS_DATA[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BUS_DATA[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BUS_DATA[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BUS_DATA[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BUS_DATA[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BUS_DATA[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BUS_DATA[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BUS_DATA[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BUS_DATA[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BUS_DATA[0]}]

set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]
set_property BITSTREAM.CONFIG.SPI_32BIT_ADDR YES [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.CONFIG.OVERTEMPPOWERDOWN ENABLE [current_design]
set_property CONFIG_MODE SPIx4 [current_design]

create_clock -period 20.000 -name FPGA_CLK_50MHZ -waveform {0.000 10.000} [get_ports FPGA_CLK_50MHZ]
set_input_delay -clock [get_clocks FPGA_CLK_50MHZ] -min -add_delay 2.000 [get_ports RST_SW]
set_input_delay -clock [get_clocks FPGA_CLK_50MHZ] -max -add_delay 15.000 [get_ports RST_SW]
set_output_delay -clock [get_clocks FPGA_CLK_50MHZ] -min -add_delay -5.000 [get_ports {BUS_DATA[*]}]
set_output_delay -clock [get_clocks FPGA_CLK_50MHZ] -max -add_delay 2.000 [get_ports {BUS_DATA[*]}]
set_output_delay -clock [get_clocks FPGA_CLK_50MHZ] -min -add_delay -5.000 [get_ports DAC_SCLK]
set_output_delay -clock [get_clocks FPGA_CLK_50MHZ] -max -add_delay 2.000 [get_ports DAC_SCLK]
set_output_delay -clock [get_clocks FPGA_CLK_50MHZ] -min -add_delay -5.000 [get_ports DAC_SDIO0]
set_output_delay -clock [get_clocks FPGA_CLK_50MHZ] -max -add_delay 2.000 [get_ports DAC_SDIO0]
set_output_delay -clock [get_clocks FPGA_CLK_50MHZ] -min -add_delay -5.000 [get_ports DAC_nCS]
set_output_delay -clock [get_clocks FPGA_CLK_50MHZ] -max -add_delay 2.000 [get_ports DAC_nCS]
set_output_delay -clock [get_clocks FPGA_CLK_50MHZ] -min -add_delay -5.000 [get_ports DAC_nRST]
set_output_delay -clock [get_clocks FPGA_CLK_50MHZ] -max -add_delay 2.000 [get_ports DAC_nRST]
set_output_delay -clock [get_clocks FPGA_CLK_50MHZ] -min -add_delay -5.000 [get_ports LATCH1_E]
set_output_delay -clock [get_clocks FPGA_CLK_50MHZ] -max -add_delay 2.000 [get_ports LATCH1_E]
set_output_delay -clock [get_clocks FPGA_CLK_50MHZ] -min -add_delay -5.000 [get_ports STS1_LED_GREEN]
set_output_delay -clock [get_clocks FPGA_CLK_50MHZ] -max -add_delay 2.000 [get_ports STS1_LED_GREEN]
set_output_delay -clock [get_clocks FPGA_CLK_50MHZ] -min -add_delay -5.000 [get_ports TP_CLK_TST]
set_output_delay -clock [get_clocks FPGA_CLK_50MHZ] -max -add_delay 2.000 [get_ports TP_CLK_TST]
