library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

-- 16-channel AD3551R driver top level.
-- Each channel is a fully independent DAC chip with its own dedicated
-- SCLK/SDIO0/nCS/nRST/nLOAD pins (per the CH0.xdc pattern), so all 16
-- channel controllers run in parallel and configure/update independently.
--
-- TO SET VOLTAGES: edit the CH_DAC_CODE table below. Each entry is the
-- 16-bit hex code written to that channel's DAC data register.
-- See the voltage-to-code formulas in the comment block below the table.

entity dac_test_16ch is
    generic (
        SIM_MODE : boolean := false
    );
    port (
        RST_SW         : in  std_logic;
        FPGA_CLK_50MHZ : in  std_logic;

        TP_CLK_TST     : out std_logic;
        STS1_LED_GREEN : out std_logic;

        DAC_nRST       : out std_logic_vector(15 downto 0);
        DAC_nLOAD      : out std_logic_vector(15 downto 0);
        DAC_nCS        : out std_logic_vector(15 downto 0);
        DAC_SCLK       : out std_logic_vector(15 downto 0);
        DAC_SDIO0      : out std_logic_vector(15 downto 0);
        DAC_SDIO2      : out std_logic_vector(15 downto 0);
        DAC_SDIO3      : out std_logic_vector(15 downto 0);

        BUS_DATA       : out std_logic_vector(15 downto 0)
    );
end dac_test_16ch;

architecture Behavioral of dac_test_16ch is

    type code_array_t is array (0 to 15) of std_logic_vector(15 downto 0);

    -- =====================================================================
    -- PER-CHANNEL OUTPUT VOLTAGE TABLE  --  EDIT THESE 16 VALUES
    --
    -- Assumes RANGE_CODE = 0x04 (+/-10V span, inherited from the original
    -- single-channel file - CONFIRM against the AD3551R datasheet).
    --
    -- Offset-binary formula, 16-bit, +/-10V span:
    --     CODE = round( (Vout + 10.0) / 20.0 * 65535 )
    --     Vout = -10.0 + CODE / 65535 * 20.0                (inverse)
    --
    -- Worked examples (+/-10V span):
    --      Vout       CODE (dec)   CODE (hex)
    --     -10.000 V        0         0x0000
    --      -5.000 V    16384         0x4000
    --       0.000 V    32768         0x8000
    --      +5.000 V    49151         0xBFFF
    --     +10.000 V    65535         0xFFFF
    --
    -- NOTE: the original single-channel file wrote x"BD9C" in a comment
    -- labeled "5V output" - under this offset-binary formula that code
    -- actually works out to ~4.81V, not exactly 5V. Before trusting the
    -- table below, verify the AD3551R datasheet's transfer-function
    -- section to confirm it really uses offset binary (code 0 = Vmin,
    -- code 0xFFFF = Vmax) rather than twos-complement bipolar coding -
    -- the two schemes give different codes for the same voltage.
    -- =====================================================================
     -- Generated by DAC code calculator | span -10V to 10V | scheme: offset binary
    -- Generated by DAC code calculator | span -10V to 10V | scheme: offset binary
    -- Generated by DAC code calculator | span -10V to 10V | scheme: offset binary
    constant CH_DAC_CODE : code_array_t := (
         0 => x"8CCC",  -- CH00 = 1.000 V
         1 => x"BFFF",  -- CH01 = 5.000 V
         2 => x"9333",  -- CH02 = 1.500 V
         3 => x"C666",  -- CH03 = 5.500 V
         4 => x"9999",  -- CH04 = 2.000 V
         5 => x"CCCC",  -- CH05 = 6.000 V
         6 => x"9FFF",  -- CH06 = 2.500 V
         7 => x"D332",  -- CH07 = 6.500 V
         8 => x"A666",  -- CH08 = 3.000 V
         9 => x"D999",  -- CH09 = 7.000 V
        10 => x"ACCC",  -- CH10 = 3.500 V
        11 => x"E666",  -- CH11 = 8.000 V
        12 => x"B333",  -- CH12 = 4.000 V
        13 => x"F332",  -- CH13 = 9.000 V
        14 => x"B999",  -- CH14 = 4.500 V
        15 => x"FFFF"  -- CH15 = 10.000 V
    );
    constant RANGE_CODE : std_logic_vector(7 downto 0) := x"04"; -- same span, all channels

    signal sclk_arr : std_logic_vector(15 downto 0);

    -- Heartbeat
    signal hb_cnt : integer range 0 to 24999999 := 0;
    signal hb_val : std_logic := '0';

begin

    BUS_DATA   <= x"AAAA";     -- unchanged from uploaded file
    TP_CLK_TST <= sclk_arr(0); -- test point mirrors channel 0's SCLK
    DAC_SCLK   <= sclk_arr;

    gen_channels : for i in 0 to 15 generate
        ch_inst : entity work.dac_ad3551r_ch
            generic map (
                SIM_MODE   => SIM_MODE,
                RANGE_CODE => RANGE_CODE,
                DAC_CODE   => CH_DAC_CODE(i)
            )
            port map (
                RST_SW         => RST_SW,
                FPGA_CLK_50MHZ => FPGA_CLK_50MHZ,
                DAC_nRST       => DAC_nRST(i),
                DAC_nLOAD      => DAC_nLOAD(i),
                DAC_nCS        => DAC_nCS(i),
                DAC_SCLK       => sclk_arr(i),
                DAC_SDIO0      => DAC_SDIO0(i),
                DAC_SDIO2      => DAC_SDIO2(i),
                DAC_SDIO3      => DAC_SDIO3(i)
            );
    end generate;

    -- 1Hz Heartbeat LED indicator (shared, unchanged from uploaded file)
    process(FPGA_CLK_50MHZ)
    begin
        if rising_edge(FPGA_CLK_50MHZ) then
            if hb_cnt = 24999999 then
                hb_cnt <= 0;
                hb_val <= not hb_val;
            else
                hb_cnt <= hb_cnt + 1;
            end if;
        end if;
    end process;
    STS1_LED_GREEN <= hb_val;

end Behavioral;