set_property PACKAGE_PIN B8 [get_ports FPGA_CLK_50MHZ]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_CLK_50MHZ]
set_property PACKAGE_PIN T14 [get_ports RS422_RX]
set_property IOSTANDARD LVCMOS33 [get_ports RS422_RX]
set_property PACKAGE_PIN P15 [get_ports RS422_TX]
set_property IOSTANDARD LVCMOS33 [get_ports RS422_TX]
set_property SLEW FAST [get_ports RS422_TX]
set_property DRIVE 12 [get_ports RS422_TX]
set_property PACKAGE_PIN R18 [get_ports RS422_TX_EN]
set_property IOSTANDARD LVCMOS33 [get_ports RS422_TX_EN]
set_property PACKAGE_PIN M13 [get_ports RS422_TX_nEN]
set_property IOSTANDARD LVCMOS33 [get_ports RS422_TX_nEN]
set_property PACKAGE_PIN T9 [get_ports STS1_LED_GREEN]
set_property IOSTANDARD LVCMOS33 [get_ports STS1_LED_GREEN]
set_property PACKAGE_PIN T10 [get_ports STS2_LED_YELLOW]
set_property IOSTANDARD LVCMOS33 [get_ports STS2_LED_YELLOW]
set_property PACKAGE_PIN A8 [get_ports TP_CLK_TST]
set_property IOSTANDARD LVCMOS33 [get_ports TP_CLK_TST]
set_property SLEW FAST [get_ports TP_CLK_TST]
set_property SLEW FAST [get_ports RS422_TX_nEN]
set_property SLEW FAST [get_ports RS422_TX_EN]
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
set_property BITSTREAM.CONFIG.SPI_32BIT_ADDR YES [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.CONFIG.OVERTEMPPOWERDOWN ENABLE [current_design]

set_property CONFIG_MODE SPIx4 [current_design]

set_property PACKAGE_PIN D10 [get_ports RST_SW]
set_property IOSTANDARD LVCMOS33 [get_ports RST_SW]

create_clock -period 20.000 -name FPGA_CLK_50MHZ -waveform {0.000 10.000} [get_ports FPGA_CLK_50MHZ]
set_input_delay -clock [get_clocks FPGA_CLK_50MHZ] -min -add_delay 1.000 [get_ports RS422_RX]
set_input_delay -clock [get_clocks FPGA_CLK_50MHZ] -max -add_delay 4.000 [get_ports RS422_RX]
set_input_delay -clock [get_clocks FPGA_CLK_50MHZ] -min -add_delay 1.000 [get_ports RST_SW]
set_input_delay -clock [get_clocks FPGA_CLK_50MHZ] -max -add_delay 4.000 [get_ports RST_SW]
set_output_delay -clock [get_clocks FPGA_CLK_50MHZ] -min -add_delay 1.000 [get_ports RS422_TX]
set_output_delay -clock [get_clocks FPGA_CLK_50MHZ] -max -add_delay 4.000 [get_ports RS422_TX]
set_output_delay -clock [get_clocks FPGA_CLK_50MHZ] -min -add_delay 1.000 [get_ports RS422_TX_EN]
set_output_delay -clock [get_clocks FPGA_CLK_50MHZ] -max -add_delay 4.000 [get_ports RS422_TX_EN]
set_output_delay -clock [get_clocks FPGA_CLK_50MHZ] -min -add_delay 1.000 [get_ports RS422_TX_nEN]
set_output_delay -clock [get_clocks FPGA_CLK_50MHZ] -max -add_delay 4.000 [get_ports RS422_TX_nEN]
set_output_delay -clock [get_clocks FPGA_CLK_50MHZ] -min -add_delay 1.000 [get_ports STS1_LED_GREEN]
set_output_delay -clock [get_clocks FPGA_CLK_50MHZ] -max -add_delay 4.000 [get_ports STS1_LED_GREEN]
set_output_delay -clock [get_clocks FPGA_CLK_50MHZ] -min -add_delay 1.000 [get_ports STS2_LED_YELLOW]
set_output_delay -clock [get_clocks FPGA_CLK_50MHZ] -max -add_delay 4.000 [get_ports STS2_LED_YELLOW]
set_output_delay -clock [get_clocks FPGA_CLK_50MHZ] -min -add_delay 1.000 [get_ports TP_CLK_TST]
set_output_delay -clock [get_clocks FPGA_CLK_50MHZ] -max -add_delay 4.000 [get_ports TP_CLK_TST]
